CustomGroup: "Intermediate Lobby"
ASide:
  - Room: "aleph_start"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: 1
        Difficulty: hard

  - Room: "aleph_entarnece"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    #- Side: Up
    #  Idx: 1
    #  Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: 1
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "aleph_main"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    #- Side: Up
    #  Idx: 1
    #  Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: 1
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none