# Ancient Engine

ASide:
  - Room: "aridai-intro"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        And:
        - Flag: sc2020_aridai_metal:set
        - Flag: poweroff:set
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "aridai-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
      LowBound: 37
    # blocked
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    Subrooms:
    - Room: "right" 
      Holes:
      - Side: Down
        Idx: 2
        Kind: in
      - Side: Right
        Idx: 0
        Kind: inout
        ReqOut:
          Or:
          - Dashes: one
            Difficulty: hard
          - Dashes: two
            Difficulty: normal
    Tweaks:
    - Name: "SpringCollab2020/FlagTouchSwitch" # "key" flag set in key room already
      Update:
        Remove: true
    - Name: "lightning" # exit locations confusing if lightning off
      Update:
        Values:
          perLevel: true
    - Name: "lightbeam" # may not actually be exit
      Update:
        Remove: true
      
  # aridai-02 cut, frustrating room in randomizer
  
  - Room: "aridai-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: hard
    - To: "touch_switches"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: hard
    - To: "top"
      ReqOut:
        Dashes: one
        And:
        - Flag: sc2020_aridai_03_switches:set
        - Flag: sc2020_aridai_metal:set
      ReqIn:
        And:
        - Flag: sc2020_aridai_03_switches:set
        - Flag: sc2020_aridai_metal:set
    Subrooms:
    - Room: "touch_switches"
      Flags:
      - sc2020_aridai_03_switches:set
    - Room: "metal_switch"
      Flags:
      - sc2020_aridai_metal:set
      Holes:
      - Side: Left
        Idx: 2
        Kind: inout
    - Room: "top"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "SpringCollab2020/SidewaysJumpThru"
      Update:
        Remove: true
      
  - Room: "aridai-03b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
        
  - Room: "aridai-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: sc2020_aridai_metal:unset
        - Dashes: one
          Difficulty: hard
          Flag: sc2020_aridai_metal:set
      ReqIn:
        Dashes: one
        Difficulty: hard
        Flag: sc2020_aridai_metal:set
    - To: "switch"
      ReqBoth:
        Flag: sc2020_aridai_metal:set
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - To: "key_flag"
      ReqBoth:
        And:
        - Flag: poweroff:set
        - Flag: sc2020_aridai_metal:set
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
    - Room: "switch"
      Flags:
      - poweroff:set
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Flag: sc2020_aridai_key:set
    - Room: "key_flag"
      Flags:
      - sc2020_aridai_key:set
    Tweaks:
    - Name: "spawn"
      X: 624
      Y: 256
      Update:
        Default: true
      
  - Room: "aridai-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "SpringCollab2020/UpsideDownJumpThru"
      Update:
        Remove: true