# Flooded Waterways

ASide:
  - Room: "Bissy_00"
    Holes:
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "left"
      ReqBoth:
        Flag: sc2020_bissy_water:unset
    - To: "up"
      ReqOut:
        Or:
        - Flag: sc2020_bissy_water:set
        - Dashes: one
          Difficulty: normal
          Flag: sc2020_bissy_touch_switch:set
        - Dashes: one
          Difficulty: perfect
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: zero
        Difficulty: normal
    - To: "right"
      ReqBoth:
        Key: true
        KeyholeID: 520
    Subrooms:
    - Room: "left"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
    - Room: "up"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "Bissy_01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "up"
      ReqOut:
        Or:
        - Flag: sc2020_bissy_water:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Or:
        - Flag: sc2020_bissy_water:set
        - Key: true
          KeyholeID: 521
          Dashes: one
          Difficulty: normal
        - Dashes: two
          Difficulty: normal
    - To: "flag_touch_switch"
      ReqOut:
        Flag: sc2020_bissy_water:set
      ReqIn:
        Dashes: zero
        Difficulty: normal
    Subrooms:
    - Room:  "flag_touch_switch"
      Flags:
      - sc2020_bissy_touch_switch:set
      - sc2020_bissy_water:unset
    - Room: "up"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
        
  - Room: "Bissy_02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "right"
      ReqIn:
        Dashes: one
        Difficulty: hard
        Flag: sc2020_bissy_water:set
    - Collectable: 0 # berry
      ReqBoth:
        Dashes: one
        Difficulty: hard
    - Collectable: 1 # key out in the open
      ReqBoth:
        Dashes: one
        Difficulty: hard
    - Collectable: 2 # key behind retract spinners
      ReqBoth:
        Dashes: one
        Difficulty: hard
        Flag: sc2020_bissy_water:unset
    Subrooms:
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        
  - Room: "Bissy_03"
    Holes:
    - Side: Left # left entrance just used to change switch state
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "switch_on"
      ReqBoth:
        Dashes: one
        Difficulty: hard
    Subrooms:
    - Room: "switch_on"
      Flags:
      - sc2020_bissy_water:set
    - Room: "up"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
        ReqOut:
          Or:
          - Flag: sc2020_bissy_water:set
          - Dashes: one
            Difficulty: normal
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Flag: sc2020_bissy_water:unset
          
  - Room: "Bissy_04"
    Hub: true
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "left"
      ReqBoth:
        Key: true
        KeyholeID: 526
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: sc2020_bissy_water:unset
        - Dashes: one
          Difficulty: hard
          Flag: sc2020_bissy_water:set
    - To: "up"
      ReqOut:
        Dashes: one
        Difficulty: normal
        Flag: sc2020_bissy_water:unset
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: sc2020_bissy_water:unset
        - Dashes: one
          Difficulty: hard
          Flag: sc2020_bissy_water:set
    - To: "right"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: sc2020_bissy_water:unset
        - Dashes: one
          Difficulty: hard
          Flag: sc2020_bissy_water:set
    - To: "berry"
      ReqBoth:
        Dashes: one
        Difficulty: normal
        Flag: sc2020_bissy_water:unset
    Subrooms:
    - Room: "left"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "right"
        ReqOut:
          Key: true
          KeyholeID: 526
        ReqIn:
          Key: true
          KeyholeID: 526
          Or:
          - Flag: sc2020_bissy_water:set
          - Dashes: one
            Difficulty: normal
            Flag: sc2020_bissy_water:unset
      - To: "up"
        ReqOut:
          Flag: sc2020_bissy_water:unset
          Key: true
          KeyholeID: 526
        ReqIn:
          Key: true
          KeyholeID: 526          
    - Room: "up"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "berry"
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "lightbeam" # may not always be top exit
      Update:
        Remove: true
    - Name: "SpringCollab2020/bubblePushField" # these tweaks allow you to return from top exit
      X: 256
      Y: 0
      Update:
        Remove: true
    - Name: "pandorasBox/flagToggleSwitch"
      Y: 104
      Update:
        Values:
          onlyOn: false
    - Name: "jumpThru"
      ID: 436
      Update:
        Width: 32
        
  - Room: "Bissy_05"
    Flags:
    - sc2020_bissy_water:set
    - sc2020_bissy_water:unset
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "top"
      ReqOut:
        Flag: sc2020_bissy_water:set
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Flag: sc2020_bissy_water:set
    Subrooms:
    - Room: "top"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout