# Electrified Resort

ASide:
  # bonicle_00 cut, uninteresting intro
      
  - Room: "bonicle_01"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      X: 112
      Y: 360
      Update:
        Remove: true
      
  - Room: "bonicle_02"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up 
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Left
        Idx: 1
        Kind: out
      - Side: Right
        Idx: 0
        Kind: out
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier" 
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      X: 608
      Y: 32
      Update:
        Remove: true
      
  - Room: "bonicle_02b"
    Holes:
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: zero
        Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier" 
      Update:
        Remove: true
      
  - Room: "bonicle_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "invisibleBarrier" 
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      X: 448
      Y: 32
      Update:
        Remove: true
      
  - Room: "bonicle_04"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 240
      Y: 752
      Update:
        Default: true
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier" 
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      X: 152
      Y: 160
      Update:
        Remove: true
    - Name: "jumpThru"
      ID: 893
      Update:
        X: 160
        Width: 16
    - Name: "jumpThru"
      ID: 894
      Update:
        Width: 24
      
  - Room: "bonicle_04b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
      
  - Room: "bonicle_05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Flag: poweroff:set
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 168
        Y: 472
    - Name: "changeRespawnTrigger"
      X: 136
      Y: 472
      Update:
        Remove: true