# Dark Side of the Moon

ASide:
  - Room: "Evilleafy_00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
      
  - Room: "Evilleafy_01"
    Holes:
    - Side: Left # in-only to allow for respawn change
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 2
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Evilleafy_02"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 485
      Update:
        Width: 32
    - Name: "jumpThru"
      ID: 1091
      Update:
        X: 320
        Width: 40
    - Name: "jumpThru"
      ID: 486
      Update:
        Width: 40
        
  - Room: "Evilleafy_03"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 870
      Update:
        Width: 48
    - Name: "towerviewer"
      Update:
        X: 760
    - Name: "spawn"
      Update:
        X: 736
      
  - Room: "Evilleafy_04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 48
      Y: 296
      Update:
        Default: true
    - Name: "jumpThru"
      ID: 1186
      Update:
        Width: 40
      
  - Room: "Evilleafy_04b"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
     
  - Room: "Evilleafy_05"
    SpinnersShatter: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in # in-only to allow for respawn change
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
      
  - Room: "Evilleafy_06"
    End: true
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 160
        Y: 48