# Hot and Cold Cavern

ASide:
  - Room: "Gabe_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: normal
    - Side: Down
      Idx: 3
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: normal
    - Side: Down
      Idx: 4
      Kind: in
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
      
  - Room: "Gabe_1B"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: two
        Difficulty: normal
      
  - Room: "Gabe_2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: normal
    # blocked
    - Side: Right
      Idx: 1
      Kind: none
      
  - Room: "Gabe_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
      
  - Room: "Gabe_intro"
    Holes:
    - Side: Down
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true