# Platform Clutter

ASide:
  - Room: "hennyburgr_intro"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "hennyburgr_1"
    Hub: true
    Holes:
    - Side: Left
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Left
      Idx: 2
      Kind: inout
    # strange
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    InternalEdges:
    - To: "up"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: normal
    - To: "upright"
      ReqBoth:
        Dashes: one
        Difficulty: normal
    - To: "downright"
      ReqBoth:
        Dashes: one
        Difficulty: normal
    - To: "down"
      ReqBoth:
        And:
        - Flag: towels:set
        - Flag: books:set
        - Flag: boxes:set
    Subrooms:
    - Room: "up"
      Holes:
      - Side: Up
        Idx: 1
        Kind: inout
    - Room: "upright"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "downright"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
    - Room: "down"
      Holes:
      - Side: Down
        Idx: 0
        Kind: inout
        ReqIn:
          Flag: towels:set
    Tweaks:
    - Name: "spawn"
      X: 240
      Y: 256
      Update:
        Default: true
    - Name: "exitBlock" # maximize chance of working big mess hub
      ID: 364
      Update:
        Remove: true
    - Name: "exitBlock"
      ID: 1019
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      ID: 1027
      Update:
        Remove: true
    - Name: "spikesRight"
      Update:
        Remove: true
        
  - Room: "hennyburgr_2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    - Side: Down
      Idx: 1
      Kind: inout
    InternalEdges:
    - To: "switch"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "switch"
      Flags: 
      - books:set
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "jumpThru"
      ID: 119
      Update:
        Width: 24
        
  - Room: "hennyburgr_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "switch"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: boxes:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - To: "berry"
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "switch"
      Flags: 
      - boxes:set
      - sc2020_hennyburgr_crates_berry:set
    - Room: "berry"
      Holes:
      - Side: Left
        Idx: 1
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Dashes: one
          Difficulty: normal
          Flag: sc2020_hennyburgr_crates_berry
    Tweaks:
    - Name: "exitBlock"
      ID: 1025
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      ID: 997
      Update:
        Remove: true
        
  - Room: "hennyburgr_4"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    InternalEdges:
    - To: "switch"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "switch"
      Collectables:
      - Idx: 0
      Flags:
      - towels:set
    Tweaks:
    - Name: "exitBlock"
      ID: 901
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      ID: 1131
      Update:
        Remove: true