# Stratcour Summit

ASide:
  - Room: "berry1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
      
  - Room: "dad1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: hard
      
  - Room: "dad2"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "dad3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
      
  - Room: "dad4"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: none
    - Side: Down
      Idx: 13
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: hard
     
  - Room: "outro1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - CustomWarp: true
      ReqOut:
        Dashes: one
        Difficulty: normal
      
  - Room: "outro2"
    ReqEnd:
      Dashes: 1
      Difficulty: normal
    Holes:
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 560
        Y: 32