# Sizzling Citadel

ASide:
  - Room: "Noax_00"
    Holes:
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
      
  - Room: "Noax_01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      
  - Room: "Noax_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Down
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
      
  - Room: "Noax_03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
      
  - Room: "Noax_04"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
      
  - Room: "Noax_S01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      
  - Room: "Noax_S02"
    Holes:
    - Side: Up
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal