# Desecration

ASide:
  - Room: "RG2_0"
    Holes:
    - Side: Down
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "RG2_1"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Flag: poweroff:set
          Difficulty: hard
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "exitBlock" 
      Update:
        Remove: true
      
  - Room: "RG2_2"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "RG2_3"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 3
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "FactoryHelper/RustyJumpthruPlatform"
      X: 72
      Y: 168
      Update:
        X: 80
        Width: 40
      
  - Room: "RG2_4"
    Holes:
    - Side: Down
      Idx: 4
      Kind: in

      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "breaker"
      ReqBoth:
        Flag: sc2020_rocketguy_fuse:set
    - To: "fuse"
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: expert
          Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: hard
          Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "breaker"
      Flags:
      - poweroff:set
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "fuse"
      Flags:
      - sc2020_rocketguy_fuse:set
      - sc2020_rocketguy_berry:set
    Tweaks:
    - Name: "jumpThru"
      ID: 137
      Update:
        Width: 32
    - Name: "spawn"
      X: 1408
      Y: 168
      Update:
        Default: true
      
  - Room: "RG2_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
    - Collectables: 0
      ReqBoth:
        Flag: sc2020_rocketguy_berry:set
    Tweaks:
    - Name: "changeRespawnTrigger"
      X: 1160
      Y: 16
      Update:
        Remove: true
      
  - Room: "RG2_5s"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none