# Another Summit

ASide:
  - Room: "IntroRoom"
    Holes:
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: normal
      Launch: 25
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
       
  # OutroRoom cut, uninteresting outro
        
  - Room: "Room1"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
      HighBound: 27
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 28
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      Update:
        X: 208
        Width: 16
      
  - Room: "Room2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      Launch: 18
    - Side: Left
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "Room3"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Dashes: two
        Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 1280
      Y: 240
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "Room4"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 1456
      Y: 992
      Update:
        Default: true