# Madelina Jones and the Temple of Zoom

ASide:
  - Room: "TheAd_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "templeGate"
      ID: 27
      Update:
        Remove: true
      
  - Room: "TheAd_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: master
    Tweaks:
    - Name: "spawn"
      X: 1072
      Y: 304
      Update:
        X: 872
        Y: 296
    - Name: "templeGate"
      ID: 107
      Update:
        Remove: true
    - Name: "jumpThru"
      ID: 667
      Update:
        X: 296
        Width: 48
      
  - Room: "TheAd_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Key: true
        KeyholeID: 12
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Collectable: 1
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "secret"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
      - Side: Up
        Idx: 0
        Kind: out
    Tweaks:
    - Name: "templeGate"
      ID: 118
      Update:
        Remove: true
      
  - Room: "TheAd_04"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left # only works with bubble
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "lockBlock"
      Update:
        Remove: true
      
  - Room: "TheAd_04_berry"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
      
  - Room: "TheAd_05"
    Core:
      All: Hot
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 80
      Y: 152
      Update:
        Default: true