# Serene Skydive

ASide:
  # 1 cut, uninteresting intro
  
  - Room: "2"
    Collectables:
    - Idx: 0
    Holes:
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Subrooms:
    - Room: "room" # hack to prevent this from being a spawn room
      Holes:
      - Side: Up
        Idx: 0
        Kind: in
        LowBound: 11
      - Side: Down
        Idx: 0
        Kind: out
        ReqOut:
          Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 16
        Y: 0
        Width: 264
        Height: 64
        Values:
          variantChange: 0 # Gravity
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 16
        Y: 0
        Width: 264
        Height: 64
        Values:
          variantChange: 1 # FallSpeed
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 16
        Y: 0
        Width: 264
        Height: 64
        Values:
          variantChange: 9 # DashLength
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 16
        Y: 0
        Width: 264
        Height: 64
        Values:
          variantChange: 12 # DashCount
          newValue: 999  
          
  - Room: "3"
    Holes:
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Subrooms:
    - Room: "room" # hack to prevent this from being a spawn room
      Holes:
      - Side: Up
        Idx: 0
        Kind: in
        LowBound: 24
      - Side: Down
        Idx: 0
        Kind: out
        ReqOut:
          Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 256
      Y: 32
      Update:
        Default: true
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 56
        Y: 0
        Width: 264
        Height: 32
        Values:
          variantChange: 0 # Gravity
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 56
        Y: 0
        Width: 264
        Height: 32
        Values:
          variantChange: 1 # FallSpeed
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 56
        Y: 0
        Width: 264
        Height: 32
        Values:
          variantChange: 9 # DashLength
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 56
        Y: 0
        Width: 264
        Height: 32
        Values:
          variantChange: 12 # DashCount
          newValue: 999  
     
  - Room: "4"
    Holes:
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Subrooms:
    - Room: "room" # hack to prevent this from being a spawn room
      Holes:
      - Side: Up
        New: true # left half of top entrance
        Kind: in
        LowBound: 0
        HighBound: 22
        HighOpen: false
      - Side: Down
        Idx: 0
        Kind: out
        ReqOut:
          Dashes: one
          Difficulty: normal
    - Room: "berry"
      Collectables:
      - Idx: 0
      Holes:
      - Side: Up # right half of top entrance
        Idx: 0
        Kind: in
        LowBound: 27
      InternalEdges:
      - To: "room" # leads to main exit
        ReqOut:
          Dashes: zero
    Tweaks:
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 320
        Height: 32
        Values:
          variantChange: 0 # Gravity
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 320
        Height: 32
        Values:
          variantChange: 1 # FallSpeed
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 320
        Height: 32
        Values:
          variantChange: 9 # DashLength
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 320
        Height: 32
        Values:
          variantChange: 12 # DashCount
          newValue: 999  
      
  - Room: "5"
    Collectables:
    - Idx: 0
    Holes:
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    Subrooms:
    - Room: "room" # hack to prevent this from being a spawn room
      Holes:
      - Side: Up
        Idx: 0
        Kind: in
        HighBound: 32
        HighOpen: false
      - Side: Right
        Idx: 0
        Kind: inout
        ReqOut:
          Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 328
        Height: 32
        Values:
          variantChange: 0 # Gravity
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 328
        Height: 32
        Values:
          variantChange: 1 # FallSpeed
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 328
        Height: 32
        Values:
          variantChange: 9 # DashLength
          newValue: 10
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 328
        Height: 32
        Values:
          variantChange: 12 # DashCount
          newValue: 999  