# Ultra Difficult

ASide:
  - Room: "0"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: master
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "1"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Dashes: one
        Difficulty: master
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Right
        Idx: 0
        Kind: out
        LowBound: 14
        HighBound: 16
      - Side: Right
        Idx: 1
        Kind: out
        LowBound: 21
        HighBound: 26
        
  - Room: "1b"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: master
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficult: master
    Tweaks:
    - Name: "SpringCollab2020/SidewaysJumpThru"
      Update:
        Remove: true
    - Name: "FrostHelper/IceSpinner"
      ID: 1723
      Update:
        Remove: true
    - Name: "FrostHelper/IceSpinner"
      ID: 1885
      Update:
        Remove: true
        
  - Room: "2"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: master
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Down
        Idx: 1
        Kind: inout
    - Room: "berry"
      Holes:
      - Side: Up
        Idx: 0
        Kind: in
      InternalEdges:
      - To: "exit"
        ReqOut:
          Dashes: one
          Difficulty: perfect
      - Collectable: 0
        ReqBoth:
          Dashes: one
          Difficulty: perfect
    Tweaks:
    - Name: "spawn"
      X: 478
      Y: 72
      Update:
        Default: true
        
  - Room: "3"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: master
    Tweaks:
    - Name: "spawn"
      X: 152
      Y: 32
      Update:
        Default: true
        
  - Room: "4"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Dashes: one
        Difficulty: master
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: master
    Subrooms:
    - Room: "exits" # can demo from one exit to the other
      Holes:
      - Side: Down
        Idx: 1
        Kind: inout
        ReqOut:
          Dashes: one
          Difficulty: expert
      - Side: Down
        Idx: 2
        Kind: inout
        ReqOut:
          Dashes: one
          Difficulty: expert
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Add: true
        X: 3896
        Y: 208
        Width: 144
        Height: 32
          
  - Room: "5"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: master
    Subrooms:
    - Room: "hard"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "exit"
        ReqOut:
          Dashes: one
          Difficulty: perfect
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 88
      Y: 104
      Update:
        Default: true
        
  # 6 cut, uninteresting outro