# Heart of the Storm

ASide:
  - Room: "CANADIAN_00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "CANADIAN_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: master
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 56
      Update:
        Default: true
      
  - Room: "CANADIAN_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
          Flag: poweroff:set
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: hard
          Flag: poweroff:set
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "berry"
        ReqOut:
          Or:
          - Dashes: one
            Difficulty: expert
          - Dashes: two
            Difficulty: hard
        ReqIn:
          Dashes: zero
          Difficulty: normal
    - Room: "berry"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 105
      Y: 320
      Update:
        Default: true
        
  - Room: "CANADIAN_03"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 2
        Kind: inout
      InternalEdges:
      - To: "berry"
        ReqOut:
          Dashes: one
          Difficulty: hard
        ReqIn:
          Dashes: zero
          Difficulty: normal
    - Room: "berry"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 64
      Y: 304
      Update:
        Default: true
        
  - Room: "CANADIAN_04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
      ReqIn:
        Dashes: zero
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "berry"
      Holes:
      - Side: Right
        Idx: 3
        Kind: inout
    Tweaks:
    - Name: "SpringCollab2020/FlagTouchSwitch" # usually this is in berry3
      Update:
        Add: true
        X: 1632
        Y: 1496
        Values:
          flag: "berry_block"
          persistent: true
    - Name: "changeRespawnTrigger"
      X: 1696
      Y: 16
      Update:
        Remove: true
        
  - Room: "CANADIAN_05"
    ReqEnd:
      Or:
      - Flag: poweroff:set
      - Dashes: one
        Difficulty: master
      - Dashes: two
        Difficulty: expert
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 2208
        Y: 1208
       
  - Room: "CANADIAN_berry"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: expert
    ExtraSpace:
    - X: 760
      Y: 1440
      Width: 160
      Height: 2336
        
  - Room: "CANADIAN_berry2"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "niceview"
      ReqOut:
        Dashes: one
        Difficulty: perfect
      ReqIn:
        Dashes: zero
        Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
    Subrooms:
    - Room: "niceview"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "SpringCollab2020/FlagTouchSwitch" # usually this is in the Nice View room
      Update:
        Add: true
        X: 5000
        Y: 176
        Values:
          flag: "berry2_block4"
          persistent: true
        
  - Room: "CANADIAN_berry3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: perfect
        
  # CANADIAN_niceview cut, uninteresting secret