# KoKoDoKo?

ASide:
  # fishtank_00 cut, uninteresting intro
  
  - Room: "fishtank_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: hard
        
  - Room: "fishtank_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out # dash block
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
        
  - Room: "fishtank_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Collectable: 0
      ReqBoth:
       Or:
       - Dashes: one
         Difficulty: expert
       - Dashes: two
         Difficulty: hard
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
          
  - Room: "fishtank_04"
    Hub: true
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: expert
    - To: "secret"
      ReqOut:
        Key: true
        KeyholeID: 830
        Dashes: one
        Difficulty: expert
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    - Room: "secret"
      Holes:
      - Side: Up
        Idx: 1
        Kind: out
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "exitBlock"
      Update:
        Remove: true
        
  - Room: "fishtank_05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up # secret exit cut, requires bubble from below
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none # secret entrance cut, requires bubble from below
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    Tweaks:
    - Name: "spinner"
      ID: 390
      Update:
        Remove: true
        
  - Room: "fishtank_06"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: perfect
    Tweaks:
    - Name: "lookoutBlocker"
      Update:
        Remove: true