# Tripeak Trail

ASide:
  - Room: "0"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 280
        Y: 168
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 88
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: perfect
        - Dashes: two
          Difficulty: expert
    Tweaks:
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
          
  - Room: "2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: expert
    Tweaks:
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
    - Name: "spawn"
      X: 40
      Y: 144
      Update:
        Default: true
    - Name: "jumpThru"
      ID: 1286
      Update:
        X: 32
        Width: 16
        
  - Room: "3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 927
      ReqOut:
        Dashes: two
        Difficulty: master
    Tweaks:
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      X: 7392
      Y: 72
      Update:
        Remove: true
       
  - Room: "4"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 74
      HighOpen: false
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: two
        Difficulty: expert
    Tweaks:
    - Name: "jumpThru"
      ID: 606
      Update:
        X: 32
        Width: 16
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true