# Temporal Tower

ASide:
  - Room: "Dav_00"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true

  - Room: "Dav_01"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
      ReqIn:
        Dashes: two
        Difficulty: normal
    Tweaks:
    - Name: "jumpThru"
      ID: 1072
      Update:
        X: 424
        Width: 32
    - Name: "spawn"
      Update:
        Add: true
        X: 144
        Y: 24
          
  - Room: "Dav_02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: 18
    - Side: Up
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
    - Collectable: 0
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
          
  - Room: "Dav_03"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
    - Collectable: 0
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: expert
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 160
        Y: 24
    - Name: "jumpThru"
      ID: 27
      Update:
        Width: 56
    - Name: "jumpThru"
      ID: 560
      Update:
        X: 416
        Width: 56
          
  - Room: "Dav_04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: 19
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
         
  # Dav_05 cut, uninteresting outro