# TheHeck90

ASide:
  - Room: "TheHeck90_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: hard
      ReqIn:
        Dashes: one
        Difficulty: normal
        Flag: poweroff:set
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 1
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 48
      Y: 128
      Update:
        Default: true
        
  - Room: "TheHeck90_02"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
          Flag: poweroff:set
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: normal
        Flag: poweroff:set
    
  - Room: "TheHeck90_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
          Flag: poweroff:set
        - Dashes: two
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: hard
        
  - Room: "TheHeck90_04"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      HighBound: 53
      HighOpen: false
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqOut:
        Dashes: two
        Difficulty: normal
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
          Flag: poweroff:set
        - Dashes: two
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: expert
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Up
        Idx: 1
        Kind: out
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 2
        Kind: inout
      InternalEdges:
      - To: "berry"
        ReqOut:
          Dashes: zero
          Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
          
  - Room: "TheHeck90_05"
    Hub: true
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left # weird troll area cut
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqOut:
      - Dashes: one
        Difficulty: normal
        Flag: poweroff:set
      - Dashes: two
        Difficulty: expert
      ReqIn:
        Dashes: one
        Difficulty: normal
        Flag: poweroff:set
    - To: "exit"
      ReqOut:
      - Dashes: one
        Difficulty: normal
        Flag: poweroff:set
      - Dashes: two
        Difficulty: expert
      ReqIn:
        Dashes: one
        Difficulty: normal
        Flag: poweroff:set
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Up
        Idx: 1
        Kind: inout
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout 
      InternalEdges:
      - To: "berry"
        ReqOut:
          Dashes: zero
          Difficulty: normal
          Flag: poweroff:set
        ReqIn:
          Dashes: one
          Difficulty: normal
          Flag: poweroff:set
    Tweaks:
    - Name: "jumpThru"
      ID: 474
      Update:
        X: 72
        Width: 24
    - Name: "towerviewer"
      Update:
        X: 88
        
  - Room: "TheHeck90_berry"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
      - Dashes: one
        Difficulty: normal
        Flag: poweroff:set
      - Dashes: two
        Difficulty: normal
      ReqIn:
        Dashes: zero
        Difficulty: normal
    - Collectable: 0
      ReqBoth:
      - Dashes: one
        Difficulty: normal
        Flag: poweroff:set
      - Dashes: two
        Difficulty: expert
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout