CustomGroup: "Beginner Lobby"
ASide:
  - Room: "Jude_00"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
      Launch: 18
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "Jude_01"
    Holes:
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 92
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
      
  - Room: "Jude_02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      Launch: 10
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 19
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "Jude_03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      Launch: 3
    - Side: Up
      Idx: 1
      Kind: out
      Launch: 24
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
      
  - Room: "Jude_04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      Launch: 4
    - Side: Up
      Idx: 2
      Kind: out
      Launch: 39
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "Jude_05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      Launch: 4
    - Side: Up
      Idx: 4
      Kind: out
      Launch: 162
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
      
  - Room: "Jude_End"
    End: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "Collab2Utils/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 232
        Y: 96