# Seeker Temple

ASide:
  # cat-00 cut, uninteresting intro
      
  - Room: "cat-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Dashes: one
        Difficulty: normal      
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
        ReqOut:
          Dashes: one
          Difficulty: normal
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  - Room: "cat-01-1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
        
  - Room: "cat-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 64
      Y: 160
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  - Room: "cat-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "berry"
      Collectables:
      - Idx: 0
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 160
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  - Room: "cat-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
        Key: true
        KeyholeID: 309
      ReqIn:
        Key: true
        KeyholeID: 309
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Left
        Idx: 2
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 80
      Update:
        Default: true
        
  # cat-05 cut, uninteresting outro