# Crystal Enigma

ASide:        
  - Room: " CookieBeg_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
        
  - Room: " CookieBeg_2"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "exitBlock"
      Update:
        Remove: true
        
  - Room: " CookieBeg_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "ExtendedVariantTrigger"
      Update:
        Height: 152
        
  - Room: " CookieBeg_4"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: perfect
        - Dashes: one
          Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: perfect
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Left
        Idx: 1
        Kind: inout
    Tweaks:
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 88
        Width: 104
        Height: 272
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "exitBlock"
      Update:
        Remove: true
          
  - Room: " CookieBeg_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none 
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 160
        Width: 104
        Height: 160
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
          
  # CookieBeg_Outro cut, uninteresting outro
          
  - Room: " CookieBeg_Strawberry1"
    Holes:
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 296
        Y: 328
        Width: 104
        Height: 56
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
          
  - Room: " CookieBeg_Strawberry2"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 216
        Y: 320
        Width: 104
        Height: 56
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
    - Name: "templeGate"
      Update:
        Remove: true
        
  - Room: " CookieBeg_Strawberry3"
    Holes:
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 24
        Y: 560
        Width: 296
        Height: 56
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
        
  - Room: " CookieBeg_intro"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true