# Electric Stratosphere

ASide:
  - Room: "DanTKO_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Flag: poweroff:set
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        ReqIn:
          Flag: poweroff:set
      InternalEdges:
      - To: "berry"
        ReqBoth:
          Dashes: one
          Difficulty: normal
    - Room: "berry"
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  - Room: "DanTKO_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqIn:
        Flag: poweroff:set
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Flag: poweroff:set
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "spawn"
      X: 64
      Y: 136
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
  
  - Room: "DanTKO_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 4
      Kind: inout
      ReqIn:
        Flag: poweroff:set
        Dashes: one
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "spawn"
      X: 152
      Y: 128
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "DanTKO_04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 3
      Kind: inout
      ReqIn:
        Flag: poweroff:set
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Flag: poweroff:set
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "jumpThru"
      ID: 52
      Update:
        X: 96
        Width: 24
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  - Room: "DanTKO_05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Flag: poweroff:set
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        ReqIn:
          Flag: poweroff:set
      InternalEdges:
      - To: "berry"
        ReqBoth:
          Dashes: one
          Difficulty: normal
    - Room: "berry"
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "jumpThru"
      ID: 917
      Update:
        X: 56
        Width: 24
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
        
  - Room: "DanTKO_Intro"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: zero
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 240
      Y: 120
      Update:
        Default: true
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  # DanTKO_Outro cut, uninteresting outro