# Blast Processing

ASide:
  - Room: "Flagpole1up_00_Intro"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
        Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
      
  - Room: "Flagpole1up_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      
  - Room: "Flagpole1up_02"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "secret"
      ReqOut:
        And:
        - Flag: sc2020_flagpole_berry:set
        - Flag: poweroff:set
      ReqIn:
        Flag: sc2020_flagpole_berry:set
    - To: "exit"
      ReqOut:
        Or:
        - Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Flag: poweroff:set
    Subrooms:
    - Room: "secret"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
        LowBound: 17
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Flag: sc2020_flagpole_berry:set
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "Flagpole1up_03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Flag: poweroff:set
        - Dashes: one
          Difficulty: normal        
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
    - Name: "jumpThru"
      ID: 284
      Update:
        X: 136
        Width: 48
      
  - Room: "Flagpole1up_04"
    Hub: true
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Or:
        - Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Flag: poweroff:set
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      - Side: Up
        Idx: 0
        Kind: inout
      
  - Room: "Flagpole1up_05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Flag: poweroff:set
        - Dashes: one
          Difficulty: normal      
    Tweaks:
    - Name: "jumpThru"
      ID: 570
      Update:
        X: 120
        Width: 40
      
  - Room: "Flagpole1up_06_Outro"
    End: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 152
        Y: 112
      
  - Room: "Flagpole1up_BerryPuzzle01"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: zero
        Difficulty: normal
      ReqIn:
        Flag: sc2020_flagpole_berry:set
    Subrooms:
    - Room: "exit"
      Flags:
      - sc2020_flagpole_berry:set
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      
  - Room: "Flagpole1up_BerryPuzzle02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
      Or:
      - Flag: poweroff:set
      - Dashes: zero
        Difficulty: perfect
      - Dashes: one
        Difficulty: normal