# Temple of the Kevins

ASide:
  - Room: "totk1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      
  - Room: "totk2"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 3
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 48
      Y: 112
      Update:
        Default: true
      
  - Room: "totk3"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqBoth:
        Dashes: one
        Difficulty: normal
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: expert
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 80
      Y: 960
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      ID: 8
      Update:
        Remove: true
    - Name: "jumpThru"
      ID: 603
      Update:
        Width: 56
    - Name: "jumpThru"
      ID: 906
      Update:
        X: 156
        Width: 48
    - Name: "everest/smoothCameraOffsetTrigger"
      X: 176
      Y: 704
      Update:
        X: 24
        Y: 744
        Width: 88
        Height: 128
    - Name: "cameraOffsetTrigger"
      ID: 1356
      Update:
        Values:
          cameraY: -0.5
    - Name: "cameraOffsetTrigger"
      Update:
        Add: true
        X: 56
        Y: 352
        Width: 32
        Height: 24
      
  - Room: "totk4"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "totk5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "totk_berry_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
      
  - Room: "totk_exit"
    ReqEnd:
      Or:
      - Dashes: zero
        Difficulty: hard
      - Dashes: one
        Difficulty: normal
    SpinnersShatter: true
    Holes:
    - Side: Down
      Idx: 1
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 272
        Y: 80
      
  - Room: "totk_intro"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
    Tweaks:
    - Name: "spawn"
      X: 56
      Y: 512
      Update:
        Default: true
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true