# Starjump

ASide:
  - Room: "1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 160
      Y: 520
      Update:
        Default: true
      
  - Room: "2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      HighBound: 26
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        LowBound: 31
        HighBound: 35
    Tweaks:
    - Name: "spawn"
      X: 224
      Y: 520
      Update:
        Default: true
      
  - Room: "3"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      HighBound: 31
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "4"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      HighBound: 31
    - Side: Left
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
   
  # "after 4" cut, uninteresting outro
      
  - Room: "pre 1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  # "pre pre 1" cut, uninteresting intro
      
  - Room: "strawberry room"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      LowBound: 31
      HighBound: 35
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal