# Heaven's Outer Space

ASide:
  - Room: "Rue_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_01_Berry_01"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      LowBound: 13
    - Side: Down
      Idx: 1
      Kind: out
      LowBound: 32
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "Rue_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: in
      LowBound: 12
      HighBound: 17
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      LowBound: 18
    - Side: Right
      Idx: 1
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_04"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: out
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: zero
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
        
   # Rue_Intro cut, uninteresting intro
   # Rue_Outro cut, uninteresting outro