# Heaven's Outer Space

ASide:
  - Room: "Rue_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Dashes: zero
        Difficulty: normal
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Up
        Idx: 0
        Kind: out  
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_01_Berry_01"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      LowBound: 13
      Launch: 16
    - Side: Down
      Idx: 1
      Kind: out
      LowBound: 32
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
      
  - Room: "Rue_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: unknown
      LowBound: 12
      HighBound: 17
      HighOpen: false
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: zero
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        LowBound: 4
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "Rue_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      LowBound: 7
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
        Difficulty: normal
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_04"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
        Difficulty: normal
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
      
  - Room: "Rue_05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
        Difficulty: normal
    - Collectable: 0
      ReqOut:
        Dashes: zero
    Tweaks:
    - Name: "SpringCollab2020/MultiRoomStrawberrySeed"
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      Update:
        Remove: true
        
   # Rue_Intro cut, uninteresting intro
   # Rue_Outro cut, uninteresting outro