# Chillout Mountain

ASide:
  - Room: "Thegur90_Beginner_0Berry"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Thegur90_Beginner_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
      
  - Room: "Thegur90_Beginner_2"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Thegur90_Beginner_3"
    Collectables:
    - Idx: 0
      MustFly: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "Thegur90_Beginner_4"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
     
  - Room: "Thegur90_Beginner_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none