# Chillout Mountain

ASide:
  - Room: "Thegur90_Beginner_0Berry"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Thegur90_Beginner_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "windAttackTrigger"
      ID: 5
      Update:
        X: 32
        Width: 32
      
  - Room: "Thegur90_Beginner_2"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
        Difficulty: normal
      ReqIn:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "windAttackTrigger"
      ID: 28
      Update:
        X: 40
        Width: 32
      
  - Room: "Thegur90_Beginner_3"
    Collectables:
    - Idx: 0
      MustFly: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 128
      Update:
        Default: true
    - Name: "windAttackTrigger"
      ID: 55
      Update:
        X: 24
        Width: 40
      
  - Room: "Thegur90_Beginner_4"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "windAttackTrigger"
      ID: 99
      Update:
        X: 24
        Width: 40
     
  - Room: "Thegur90_Beginner_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "windAttackTrigger"
      ID: 104
      Update:
        X: 32
        Width: 40
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true