# Beginner Heartside

ASide:
  # beg_heart_00 cut, uninteresting intro
  
  - Room: "beg_heart_01"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 252
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    Tweaks:
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
      
  - Room: "beg_heart_02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      HighBound: 40
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
      
  - Room: "beg_heart_03"
    Holes:
    - Side: Left
      Idx: 2
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
      
  - Room: "beg_heart_04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
      
  - Room: "beg_heart_05"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Key: true
        KeyholeID: 2612
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
   
  - Room: "beg_heart_06"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
      
  - Room: "beg_heart_07"
    ReqEnd:
      Dashes: 1
      Difficulty: normal
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none