Campaigns:
  - Name: "Spring Collab 2020"
    LevelSets:
    - Name: "Beginner Lobby"
      ID: "SpringCollab2020/1-Beginner"
    - Name: "Intermediate Lobby"
      ID: "SpringCollab2020/2-Intermediate"
    - Name: "Advanced Lobby"
      ID: "SpringCollab2020/3-Advanced"
    - Name: "Expert Lobby"
      ID: "SpringCollab2020/4-Expert"
    - Name: "Grandmaster Lobby"
      ID: "SpringCollab2020/5-Grandmaster"
    
CollectableNames:
  - "SpringCollab2020/returnBerry"
    
Music:
  # Lobbies
  - Name: "event:/collab2020/lobbytest"
  - Name: "event:/collab2020/beginner_lobby"
  - Name: "event:/SC2020_Int_Lobby"
  - Name: "event:/SC2020_Lobby_advanced"
  # Beginner maps
  - Name: "event:/SC2020_Jude"
  - Name: "event:/collab2020/bissy_beginner"
  - Name: "event:/SC2020_canadian_int"
  - Name: "event:/SC2020_Cruor"
  - Name: "event:/Collab2020/Flagpole1Up"
  - Name: "event:/SC2020_HennyBurgr"
  - Name: "event:/SC2020_dad_kevinTemple"
  - Name: "event:/SC2020_Choco"
  - Name: "event:/SC2020_Rue_Beginner"
  - Name: "event:/SC2020_skeleton_beginner"
  - Name: "event:/SC2020_TG90BEG"
  - Name: "event:/collab2020/heartside_beginner"
  # Intermediate maps
  - Name: "event:/SC2020_aleph_int"
  - Name: "event:/SC2020_aridai_int"
  - Name: "event:/SC2020_Bissy_Intermed"
  - Name: "event:/SC2020_Hyper"
  - Name: "event:/collab2020/donker"
  - Name: "event:/SC2020_EvilLeafy"
  - Name: "event:/SC2020_Goat_Collab"
  - Name: "event:/SC2020_Collab_Lichtbaulb_Intermediate-3.5"
  - Name: "event:/SC2020_Noax"
  - Name: "event:/collab2020/oppen"
  - Name: "event:/music/phant_collab"
  - Name: "event:/SC2020_Rocketguy_collab"
  - Name: "event:/SC2020_Collab_Skeleton_Intermediate-3.5"
  - Name: "event:/SC2020_TheA_In"
  - Name: "event:/SC2020_TheA_Esc"
  - Name: "event:/SC2020_Thegur90_Intermediate"
  - Name: "event:/SC2020_Int_Heartside"