# Electric Exuberance

ASide:
  - Room: "1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: none
    - Side: Down
      Idx: 13
      Kind: none
    - Side: Down
      Idx: 14
      Kind: none
    - Side: Down
      Idx: 15
      Kind: none
    - Side: Down
      Idx: 16
      Kind: none
    - Side: Down
      Idx: 17
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "2b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
          Flag: poweroff:set
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
          Flag: poweroff:set
      LowBound: 58
      HighBound: 61
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
      
  - Room: "3"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: expert
    Tweaks:
    - Name: "jumpThru" 
      Update:
        Width: 32
      
  - Room: "4"
    Holes:
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: expert
    Tweaks:
    - Name: "killbox"
      ID: 291
      Update:
        Remove: true
    - Name: "jumpThru"
      X: 736
      Update:
        Width: 32
      
  - Room: "5b"
    Holes:
    - Side: Down
      Idx: 3
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
      LowBound: 39
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: expert
    Tweaks:
    - Name: "jumpThru"
      Update:
        X: 640
        Width: 32
      
  - Room: "6"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true