# Ligament

ASide:
  - Room: "Kube_1"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Key: true
        KeyholeID: 27
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: hard
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "Kube_2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
      
  - Room: "Kube_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    InternalEdges:
    - Collectable: 0 # key
      ReqBoth:
        Dashes: one
        Difficulty: hard
    - Collectable: 1 # berry
      ReqBoth:
        Dashes: one
        Difficulty: hard
  
  - Room: "Kube_4"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Kube_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Kube_5a"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down # cut, autobubble doesn't take to this spawn
      Idx: 3
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: hard
      
  - Room: "Kube_6"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    # strange
    - Side: Up
      Idx: 0
      Kind: unknown
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Kube_7"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Side: Right
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
      
  - Room: "Kube_b1"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: perfect
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
        
  - Room: "Kube_b2"
    End: true
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 60
        Y: 88