# High Voltage

ASide:
  - Room: "?2"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: expert
        Flag: poweroff:set
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "?3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "?4"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "?5"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: expert
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Up
        Idx: 3
        Kind: out
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 4
        Kind: inout
      InternalEdges:
      - To: "berry"
        ReqOut:
          Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "jumpThru"
      Update:
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 584
        Y: 32
      
  - Room: "?6"
    Hub: true
    Holes:
    - Side: Down
      Idx: 2
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Up
      Idx: 10
      Kind: none
    - Side: Up
      Idx: 11
      Kind: none
    - Side: Up
      Idx: 12
      Kind: none
    - Side: Up
      Idx: 13
      Kind: none
    - Side: Up
      Idx: 14
      Kind: none
    - Side: Up
      Idx: 15
      Kind: none
    - Side: Up
      Idx: 16
      Kind: none
    - Side: Up
      Idx: 17
      Kind: none
    - Side: Up
      Idx: 18
      Kind: none
    - Side: Up
      Idx: 19
      Kind: none
    - Side: Up
      Idx: 20
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: none
    - Side: Down
      Idx: 13
      Kind: none
    - Side: Down
      Idx: 14
      Kind: none
    - Side: Down
      Idx: 15
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: two
          Difficulty: hard
      ReqIn:
        Dashes: two
        Difficulty: hard
        Flag: poweroff:set
    Subrooms:
    - Room: "exit"
      Flags:
      - poweroff:set
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        ReqBoth:
          Flag: poweroff:set
      InternalEdges:
      - To: "secret"
        ReqBoth:
          Dashes: one
          Difficulty: normal
          Flag: poweroff:set
    - Room: "secret"
      Holes:
      - Side: Up
        Idx: 8
        Kind: inout
        ReqBoth:
          Flag: poweroff:set
    - Room: "berry"
      Collectables:
      - Idx: 0
      Holes:
      - Side: Down
        Idx: 1
        Kind: in
      InternalEdges:
      - To: "main"
        ReqOut:
          Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "jumpThru"
      ID: 505
      Update:
        Width: 24
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
          
  - Room: "?s"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
      Or:
      - Dashes: one
        Difficulty: hard
      - Dashes: two
        Difficulty: normal