# Blank Dreams

ASide:
  - Room: "Zerex_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Zerex_03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "SpringCollab2020/ChangeThemeTrigger"
      Update:
        Remove: true
      
  - Room: "Zerex_04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      HighBound: 15
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "Zerex_05"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      LowBound: 8
      HighBound: 15
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      LowBound: 64
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
      LowBound: 12
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "dreamBlock"
      ID: 458
      Update:
        Y: 0
        Height: 16
      
  - Room: "Zerex_05b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      LowBound: 14
      HighBound: 16
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "dreamBlock"
      ID: 556
      Update:
        Height: 36
      
  - Room: "Zerex_06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      LowBound: 9
      HighBound: 12
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: expert
      HighBound: 3
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none