# Blank Dreams

ASide:
  - Room: "Zerex_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 512
      Y: 128
      Update:
        Default: true
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "jumpThru"
      Update:
        Width: 16
      
  - Room: "Zerex_03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    Tweaks:
    - Name: "SpringCollab2020/ChangeThemeTrigger"
      Update:
        Remove: true
      
  - Room: "Zerex_04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      LowBound: 8
    - Side: Right
      Idx: 0
      Kind: inout
      LowBound: 8
      HighBound: 15
      HighOpen: false
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
    Tweaks:
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
      
  - Room: "Zerex_05"
    Hub: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      LowBound: 8
      HighBound: 15
      HighOpen: false
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      LowBound: 64
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
      LowBound: 11
      HighBound: 12
      HighOpen: false
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "dreamBlock"
      ID: 458
      Update:
        Y: 0
        Height: 16
      
  - Room: "Zerex_05b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      LowBound: 14
      HighBound: 16
      HighOpen: false
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "dreamBlock"
      ID: 556
      Update:
        Remove: true
      
  - Room: "Zerex_06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      LowBound: 9
      HighBound: 12
      HighOpen: false
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 3
      HighOpen: false
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: expert
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true