# Above Celeste's Peak

ASide:
  - Room: "room_0"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "room_1"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 480
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      X: 1224
      Y: 304
      Update:
        Remove: true
          
  - Room: "room_2"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Or:
          - Dashes: one
            Difficulty: hard
          - Dashes: two
            Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 48
      Y: 216
      Update:
        Default: true
      
  - Room: "room_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: none
    - Side: Down
      Idx: 13
      Kind: none
    - Side: Down
      Idx: 14
      Kind: none
    - Side: Down
      Idx: 15
      Kind: none
    - Side: Down
      Idx: 16
      Kind: none
    - Side: Down
      Idx: 17
      Kind: none
    - Side: Down
      Idx: 18
      Kind: none
    - Side: Down
      Idx: 19
      Kind: none
    - Side: Down
      Idx: 20
      Kind: none
    - Side: Down
      Idx: 21
      Kind: none
    - Side: Down
      Idx: 22
      Kind: none
    - Side: Down
      Idx: 23
      Kind: none
    - Side: Down
      Idx: 24
      Kind: none
    - Side: Down
      Idx: 25
      Kind: none
    - Side: Down
      Idx: 26
      Kind: none
    - Side: Down
      Idx: 27
      Kind: none
    - Side: Down
      Idx: 28
      Kind: none
    - Side: Down
      Idx: 29
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: hard
    Subrooms:
    - Room: "cut_berry" # workaround until can disable, requires bubble from other room
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
      
  - Room: "room_4"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none