# The Climb

ASide: 
  - Room: "Holly_01"
    Hub: true
    Holes:
    - Side: Left
      Idx: 6
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 5
      Kind: none
    - Side: Right
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "middle1"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "middle1"
      Holes:
      - Side: Left
        Idx: 5
        Kind: inout
      InternalEdges:
      - To: "middle2"
        ReqOut:
          Dashes: one
          Difficulty: normal
        ReqIn:
          Dashes: zero
    - Room: "middle2"
      Holes:
      - Side: Left
        Idx: 4
        Kind: inout
      InternalEdges:
      - To: "top"
        ReqOut:
          Or:
          - Dashes: one
            Difficulty: hard
          - Dashes: two
            Difficulty: normal
        ReqIn:
          Dashes: zero
    - Room: "top"
      Holes:
      - Side: Up
        Idx: 3
        Kind: inout
    Tweaks:
    - Name: "player"
      X: 32
      Y: 536
      Update:
        Default: true
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 864
        Width: 144
        Height: 72
        Values:
          variantChange: 41 # DisableNeutralJumping
          newValue: 1
      
  - Room: "Holly_01b"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Left
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 280
      Y: 224
      Update:
        Default: true
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 248
        Y: 72
        Width: 72
        Height: 152
        Values:
          variantChange: 41 # DisableNeutralJumping
          newValue: 1
      
  - Room: "Holly_02"
    Hub: true
    Holes:
    - Side: Down
      Idx: 3
      Kind: in
    - Side: Up
      Idx: 2
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Up
      Idx: 8
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Dashes: two
        Difficulty: hard
    Subrooms:
    - Room: "berry"
      Collectables:
      - Idx: 0
      Holes:
      - Side: Up
        Idx: 9
        Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 904
        Y: 80
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 88
        Y: 440
        Width: 144
        Height: 72
        Values:
          variantChange: 41 # DisableNeutralJumping
          newValue: 1
      
  - Room: "Holly_03"
    Holes:
    - Side: Down
      Idx: 4
      Kind: inout
    - Side: Down
      Idx: 5
      Kind: unknown
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 6
      Kind: none
    - Side: Right
      Idx: 7
      Kind: none
    - Side: Right
      Idx: 8
      Kind: none
    - Side: Right
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    InternalEdges:
    - To: "botright"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "topleft"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "topright"
        ReqOut:
          Dashes: one
          Difficulty: normal
      - To: "main"
        ReqOut:
          Dashes: zero
    - Room: "topright"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "botright"
        ReqOut:
          Dashes: zero
    - Room: "botright"
      Holes:
      - Side: Right
        Idx: 5
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 229
      Y: 272
      Update:
        Default: true
    - Name: "spawn"
      X: 152
      Y: 344
      Update:
        Remove: true
    - Name: "jumpThru"
      Update:
        Width: 24
    - Name: "changeRespawnTrigger"
      Update:
        Remove: true
    - Name: "towerviewer"
      Update:
        Add: true
        X: 80
        Y: 352
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 88
        Y: 280
        Width: 144
        Height: 72
        Values:
          variantChange: 41 # DisableNeutralJumping
          newValue: 1
      
  - Room: "Holly_04"
    Holes:
    - Side: Left
      Idx: 5
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Left
      Idx: 7
      Kind: none
    - Side: Left
      Idx: 8
      Kind: none
    - Side: Left
      Idx: 9
      Kind: none
    - Side: Left
      Idx: 10
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "rumble"
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - To: "exit"
      ReqOut:
        Flag: sc2020_holly_rumble:set
        Dashes: one
      ReqIn:
        Flag: sc2020_holly_rumble:set
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
    - Room: "rumble"
      Flags:
      - sc2020_holly_rumble:set
    Tweaks:
    - Name: "spawn"
      X: 24
      Y: 448
      Update:
        Default: true
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 384
        Width: 144
        Height: 72
        Values:
          variantChange: 41 # DisableNeutralJumping
          newValue: 1
      
  - Room: "Holly_05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 1200
      Y: 960
      Update:
        Default: true
    - Name: "ExtendedVariantTrigger"
      Update:
        Add: true
        X: 1146
        Y: 896
        Width: 144
        Height: 72
        Values:
          variantChange: 41 # DisableNeutralJumping
          newValue: 1