# Mural Skies

ASide:
  - Room: "1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 112
      Y: 120
      Update:
        Default: true
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 80
        Y: 72
        Width: 64
        Height: 64
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
    - Name: "DJMapHelper/climbBlockerTrigger" # fullscreen, non-persistent
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 1280
        Height: 184
        Values:
          wallJump: true
      
  - Room: "2"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: master
        - Dashes: two
          Difficulty: hard
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 0
        Y: 104
        Width: 64
        Height: 64
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
    - Name: "DJMapHelper/climbBlockerTrigger" # fullscreen, non-persistent
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 1720
        Height: 184
        Values:
          wallJump: true
      
  - Room: "3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 16
        Y: 104
        Width: 64
        Height: 64
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
    - Name: "DJMapHelper/climbBlockerTrigger" # fullscreen, non-persistent
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 1440
        Height: 184
        Values:
          wallJump: true
      
  - Room: "4"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "ExtendedVariantMode/ExtendedVariantTrigger"
      Update:
        Add: true
        X: 8
        Y: 120
        Width: 64
        Height: 64
        Values:
          variantChange: "DisableNeutralJumping"
          newValue: 1
    - Name: "DJMapHelper/climbBlockerTrigger" # fullscreen, non-persistent
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 1120
        Height: 184
        Values:
          wallJump: true