# Cave-in Cavern

ASide:
  - Room: "spoopy_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "spoopy_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 3
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # strange
    - Side: Right
      Idx: 0
      Kind: unknown
    # blocked
    - Side: Left # secret entrance not interesting
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "changeRespawnTrigger"
      X: 88
      Y: 736
      Update:
        Remove: true
      
  - Room: "spoopy_03"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: hard
    Subrooms:
    - Room: "exit"
      Collectables:
      - Idx: 0
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      
  - Room: "spoopy_04"
    Hub: true
    Holes:
    - Side: Right
      Idx: 2
      Kind: inout
    # blocked
    - Side: Right # key entrance not interesting
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
    - Collectable: 1
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - To: "secret"
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Subrooms:
    - Room: "secret"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
    - Room: "exit"
      Holes:
      - Side: Down
        Idx: 0
        Kind: inout
        HighBound: 4
        Launch: -1
    - Room: "key" # key uninteresting, cut
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "fakeWall" 
      ID: 173
      Update:
        Remove: true
    - Name: "spawn"
      Update:
        Add: true
        X: 16
        Y: 320
    - Name: "jumpThru"
      Update:
        Add: true
        X: 8
        Y: 320
        Width: 16
    ExtraSpace:
    - X: 128
      Y: 344
      Width: 16
      Height: 80
     
  - Room: "spoopy_05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 3
      Kind: inout
    # blocked
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right # space gravity entrances not interesting
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Collectable: 0
      ReqBoth:
        Key: true
        KeyholeID: 968
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
        
  - Room: "spoopy_06"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Up
      Idx: 10
      Kind: none
    - Side: Up
      Idx: 11
      Kind: none
    - Side: Up
      Idx: 12
      Kind: none
    - Side: Up
      Idx: 13
      Kind: none
    - Side: Up
      Idx: 14
      Kind: none
    - Side: Up
      Idx: 15
      Kind: none
    - Side: Up
      Idx: 16
      Kind: none
    - Side: Up
      Idx: 17
      Kind: none
    - Side: Up
      Idx: 18
      Kind: none
    - Side: Up
      Idx: 19
      Kind: none
    - Side: Up
      Idx: 20
      Kind: none
    - Side: Up
      Idx: 21
      Kind: none
    - Side: Up
      Idx: 22
      Kind: none
    - Side: Up
      Idx: 23
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: none
    - Side: Down
      Idx: 13
      Kind: none
    - Side: Down
      Idx: 14
      Kind: none
    - Side: Down
      Idx: 15
      Kind: none
    - Side: Down
      Idx: 16
      Kind: none
    - Side: Down
      Idx: 17
      Kind: none
    - Side: Down
      Idx: 18
      Kind: none
    - Side: Down
      Idx: 19
      Kind: none
    - Side: Down
      Idx: 20
      Kind: none
    - Side: Down
      Idx: 21
      Kind: none
    - Side: Down
      Idx: 22
      Kind: none
    - Side: Down
      Idx: 23
      Kind: none
    - Side: Down
      Idx: 24
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 107
      Y: 144
      Update:
        Default: true