# Cave-in Cavern

ASide:
  - Room: "spoopy_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "spoopy_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 3
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # strange
    - Side: Right
      Idx: 0
      Kind: unknown
    # blocked
    - Side: Left # secret entrance not interesting
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
      
  - Room: "spoopy_03"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: hard
      
  - Room: "spoopy_04"
    Holes:
    - Side: Right
      Idx: 2
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Right # key + key entrance not interesting
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Collectable: 1
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
     
  - Room: "spoopy_05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 3
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right # space gravity entrances not interesting
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Key: true
        KeyholeID: 968
        
  - Room: "spoopy_06"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Up
      Idx: 10
      Kind: none
    - Side: Up
      Idx: 11
      Kind: none
    - Side: Up
      Idx: 12
      Kind: none
    - Side: Up
      Idx: 13
      Kind: none
    - Side: Up
      Idx: 14
      Kind: none
    - Side: Up
      Idx: 15
      Kind: none
    - Side: Up
      Idx: 16
      Kind: none
    - Side: Up
      Idx: 17
      Kind: none
    - Side: Up
      Idx: 18
      Kind: none
    - Side: Up
      Idx: 19
      Kind: none
    - Side: Up
      Idx: 20
      Kind: none
    - Side: Up
      Idx: 21
      Kind: none
    - Side: Up
      Idx: 22
      Kind: none
    - Side: Up
      Idx: 23
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 11
      Kind: none
    - Side: Down
      Idx: 12
      Kind: none
    - Side: Down
      Idx: 13
      Kind: none
    - Side: Down
      Idx: 14
      Kind: none
    - Side: Down
      Idx: 15
      Kind: none
    - Side: Down
      Idx: 16
      Kind: none
    - Side: Down
      Idx: 17
      Kind: none
    - Side: Down
      Idx: 18
      Kind: none
    - Side: Down
      Idx: 19
      Kind: none
    - Side: Down
      Idx: 20
      Kind: none
    - Side: Down
      Idx: 21
      Kind: none
    - Side: Down
      Idx: 22
      Kind: none
    - Side: Down
      Idx: 23
      Kind: none
    - Side: Down
      Idx: 24
      Kind: none