# Crumbling Castle
ASide:
  - Room: "ATortoise_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Key: true
        KeyholeID: 173
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    # blocked
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
      
  - Room: "ATortoise_Intro"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
        
  - Room: "BTortoise_B1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: out
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down # key entrance cut
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "cut_key" # workaround until can disable, key not interesting
      Collectables:
      - Idx: 1
      
  - Room: "BTortoise_Outro"
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 438
        Y: 184
        
  - Room: "CTortoise_B2"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
      
  - Room: "Tortoise_2"
    Collectables:
    - Idx: 1
    Holes:
    - Side: Left
      Idx: 2
      Kind: in
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
    # blocked
    - Side: Left # bubble entrance, will cut for now
      Idx: 1
      Kind: none
    # InternalEdges: # cut for now, would have to be only exit
    # - CustomWarp: true
      # ReqOut:
        # Key: true
        # KeyholeID: 802
    Subrooms:
    - Room: "upper"
      Collectables:
      - Idx: 0
      Holes:
      - Side: Right # for now... routing will be complicated
        Idx: 1
        Kind: in
      - Side: Left
        Idx: 0
        Kind: out
        ReqOut:
          Or:
          - Dashes: zero
            Difficulty: hard
          - Dashes: one
            Difficulty: normal
      - Side: Right
        Idx: 0
        Kind: out
        ReqOut:
          Dashes: one
          Difficulty: normal
      
  - Room: "Tortoise_3"
    Holes:
    - Side: Left # warp-in room
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
      
  - Room: "Tortoise_3B"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges: # cut for now, would have to be only exit
    - CustomWarp: true
      
  - Room: "Tortoise_4"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left # random secret, cut
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
      
  - Room: "Tortoise_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal