# Advanced Heart Side
ASide:
  - Room: "Heartside_1"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: 1
          Difficulty: expert
        - Dashes: 2
          Difficulty: hard
    # blocked
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
      
  - Room: "Heartside_2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: 1
          Difficulty: expert
        - Dashes: 2
          Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "spinner"
      ID: 1685
      Update:
        Remove: true
    - Name: "spinner"
      ID: 1686
      Update:
        Remove: true
      
  - Room: "Heartside_3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "Heartside_4"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Or:
        - Dashes: 1
          Difficulty: expert
        - Dashes: 2
          Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none